[connection]
brokers = ["kafka1:9093"]
use_ssl = true

[connection.ssl]
ca_file = "/run/secrets/ca-cert"
server_verification_required = true
client_cert_file = "/run/secrets/classifier-unit-cert"
client_key_file = "/run/secrets/classifier-unit-key"
client_key_password = "$$PASS_KEY_CLASSIFIER_UNIT$$"
check_hostname = true

[consumer]
# Options passed directly to confluent-kafka and its underlying librdkafka library.
# The dotted keys must be enclosed in "".
# See: https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md
"session.timeout.ms" = 10000
"auto.commit.interval.ms" = 3000

[producer]
# Same as above.
"compression.codec" = "zstd"
"linger.ms" = 1000
"batch.num.messages" = 10000
"request.required.acks" = "all"
"message.send.max.retries" = 100

[logging.client]
min_level = "DEBUG"
stdout_level = "DEBUG"
stderr_level = "INFO"

[logging.worker]
min_level = "DEBUG"
stdout_level = "DEBUG"
stderr_level = "INFO"

[client]
app_id = "$$ID_PREFIX$$-classifier-unit"
mp_start_method = "forkserver"
workers = 8
classifier_impl = "production"
poll_timeout = 3.0
worker_kill_timeout = 5.0
liveliness_check_interval = 10.0
init_wait = 5.0
max_entries_to_confirm = 16

entry_late_warning_threshold = 60.0
max_entry_time_in_queue = 150.0

max_queued_items = 16
resume_after_freed_items = 4

[production-classifier]
base_dir = "/opt/pysetup/.venv/lib/python3.11/site-packages/classifiers"
