[connection]
brokers = ["aiokafka://kafka1:9093"]
use_ssl = true

[connection.ssl]
ca_file = "/run/secrets/ca-cert"
server_verification_required = true
client_cert_file = "/run/secrets/collector-cert"
client_key_file = "/run/secrets/collector-key"
client_key_password = "$$PASS_KEY_COLLECTOR$$"
check_hostname = true

[dns.faust]
producer_compression_type = "zstd"

[dns]
app_id = "domrad-dns"
log_level = "INFO"
log_level_stderr = "WARNING"
debug = false
dns_servers = [$$DNS_RESOLVERS$$]
timeout = 5
rotate_nameservers = true
use_one_socket = true
concurrency = 16

[dns.consumer]
max_poll_records = 50
