kafka:
  clusters:
    - name: the-cluster
      bootstrapServers: kafka1:9093
      properties:
        security:
          protocol: SSL
        ssl:
          keystore:
            location: "/run/secrets/kafka-ui-keystore"
            password: "$$PASS_KEY_KAFKA_UI$$"
          truststoreLocation: "/run/secrets/kafka-truststore"
          truststorePassword: "$$PASS_TRUSTSTORE$$"
      kafkaConnect:
        - name: the-connect
          address: "http://kafka-connect:8083"

auth:
  type: "LOGIN_FORM"

spring:
  security:
    user:
      name: ""